### PR TITLE
Adding support for ES6 in eslint 

### PR DESCRIPTION
**Pull request by Tubaleviao**

### CODE REVIEW

**Comment by Tubaleviao** [comment]
Is that possible to make Travis CI execute first "npm install" before "npm ci"?

**Comment by sffc** [comment]
To make Travis CI happy you need to update the package-lock.json file.  Since you updated some of the dependency versions in package.json, there should also be changes in package-lock.json.

**Comment by Tubaleviao** [comment]
But the package-lock.json is listed in the .gitignore file... So it shouldn't be getting modifications.

**Comment by sffc** [comment]
I removed it from .gitignore in #96; maybe you need to pull the latest changes?

**Comment by Tubaleviao** [comment]
I've opened another pull request for this change (#99 )

**Pull request closed without merging**
