### PR TITLE
Set up eslint and generally cleaned up the files

### PR DESCRIPTION
**Pull request by MaffooBristol**
Hashtag untested.

Keeps the tabs and general current coding style, but uses single quotes, no combined `var` definitions, checks for semicolons, mixed tabs/spaces, etc. I also changed the way the block comments are structured so that they work better with multiline descriptions without having to reshuffle the indentation and stuff. Basically the Drupal docblock format. Also just a few minor modifications to comments, but absolutely 0% of it is actual operative code changes.

A large lot of it looks more changed than it is in the diff due to properly indenting the majority of client.js!

Thoughts? 😄 

Cheers,
Matt

### CODE REVIEW

**Comment by vote539** [comment]
Thanks for the PR; it's probably time that the code formatting got cleaned up a bit.  At first glance, I like the changes to the comment blocks, semicolons, and `var` definitions.

The big block in the middle of *client.js* has been missing one level of indentation since de264e8, when support was added for AMD.  Although it would probably be better for the code to be re-indented, I chose to leave it the way it was in order to minimize the number of lines that were touched.  If a commit touches too many lines, it screws up "git blame" code history.

Regarding the quote style, I'm not particularly attached to one version over the other, but double quotes are more common right now than single quotes, so single-to-double would touch fewer lines than double-to-single.

In order to minimize the number of lines that get touched, would you consider changing the lint settings (1) to suppress the indentation of the big block in the middle of *client.js*, and (2) to use double quotes instead of single quotes?  For the first one, maybe something like [this](http://eslint.org/docs/rules/indent#outeriifebody) would work?

**Comment by MaffooBristol** [comment]
Hi vote, sorry for the late reply!

I entirely understand about not affecting too many lines, although a simple whitespace flag negates that, but yeah I get its best not to entirely rewrite but not actually change anything! The issue with changing the eslint config is that it will either ignore that indentation, but also ignore any possible issues of indentation into the future, or just always fail on one line. Either that line is indented and everything past it that's left as is explodes, or it's kept the same/undented and there's one line of error. So not sure about what to do with that.

As for the single vs double thing, I'm not quite sure why you're getting the double quotes is more common thing from as most repos I've seen are single quotes- and socket.io itself is, which may be a good baseline for style guides? But it's your project so if you'd prefer doubles then that's coooool :smile: and I've also just realised that you mean more common in SIOFU, sorry ha. But I'm on mobile so can't be bothered deleting my previous ramblings. I do think they should be singles but it's all oranges and lemons and apples or whatever.

But yeah, I'll revert the big changes if you'd prefer that?

Ps. Apologies for any confusing sentences, beer+mobile isn't the best combination for githubbing ;)

Thanks! Matt

**Comment by vote539** [comment]
I think there's a way to make eslint ignore indentation on specific lines/blocks only.  It should still complain about indentation elsewhere.  eslint is very configurable.

**Comment by MaffooBristol** [comment]
Okay cool, thanks. I'll have a play with it then in that case!

**Pull request closed without merging**
