### PR TITLE
Testing migration to es6 in server.js

### PR DESCRIPTION
**Pull request by Tubaleviao**

### CODE REVIEW

**Comment by Tubaleviao** [comment]
Is Travis CI really working? I just changed the server.js this time and I didn't changed much.

**Comment by sffc** [comment]
There's something strange going on with Travis CI.  I'll try fiddling with it.

**Comment by sffc** [comment]
#96

**Comment by sffc** [comment]
OK, I fixed the Travis build error and re-ran the build for this PR.  It is still failing, but this time due to a linting error in the PR.

**Comment by Tubaleviao** [comment]
Wow, looks like the error is coming from server.js, I'm just modifying the client.js: 
```
/home/travis/build/sffc/socketio-file-upload/server.js
  678:40  error  Parsing error: Unexpected token >
```

**Comment by sffc** [comment]
You might have to update the ES version in travis.yml to get the parsing to work.  Feel free to update it as much as you want; this will in any case be a breaking change so I will be bumping the major version number.

**Comment by Tubaleviao** [comment]
Making new pull request with eslint version updated

**Pull request closed without merging**
