### PR TITLE
Some new flags

### PR DESCRIPTION
**Pull request by birdy90**
* server: 
1. flag for disalowwing duplicate files, 
2. flag to put to subdirectories if name is longer than 4 symbols
* client: 
1. flag to allow hash names of files (hash is built by file contents and is counted by file parts, so very big files will hash succesfully)

I made this changes not affect any previous code, so hope it won't break anything on other people's projects

if you merge this changes to repository, i would like to know when they will be available on npm?

### CODE REVIEW

**Comment by birdy90** [comment]
To use name hashing of uploaded files, you need to include [SparkMD5.js](https://github.com/satazor/js-spark-md5) lib before including client.js file
```html
<script src="/javascripts/spark-md5.min.js"></script>
<script src='/javascripts/client.js'></script>
```

**Comment by birdy90** [comment]
needs some improvements and testing

**Comment by vote539** [comment]
Dear birdy90,

Thank you for the pull request!  I need you to do a couple of things before it is merged:

1. Please resolve the merge conflicts.
2. There are large sections of code that changed due to indentation.  Please do not touch any lines from the file unless you are actually changing the code on those lines.  This is to ensure that "git blame" works as far into the history as possible.

Shane

**Comment by sffc** [comment]
I'm going to close this PR due to inactivity.  Feel free to re-open it once you resolve the requests listed above.

**Pull request closed without merging**
